// projects/vue-demos/src/7guis/Counter.vue
<script setup lang="ts">
import { useRemeshDomain, useRemeshQuery } from 'remesh-vue'
import { Counter } from 'remesh-domains-for-demos/dist/7guis/Counter'

const counterDomain = useRemeshDomain(Counter())

const count = useRemeshQuery(counterDomain.query.count())

const handleIncre = () => {
  counterDomain.command.incre()
}
</script>

<template>
  <div
    :style="{
      width: '400px',
      border: '1px solid #eaeaea',
      boxSizing: 'border-box',
      padding: '10px',
    }"
  >
    <h2>Counter</h2>
    <input type="number" readonly :value="count" />
    <label>
      <button @click="handleIncre">Count</button>
    </label>
  </div>
</template>

// projects/remesh-example/src/7guis/Counter.tsx
import React from 'react';

import { Remesh } from 'remesh';
import {
  useRemeshDomain,
  useRemeshQuery,
} from "remesh-react";

const Counter = Remesh.domain({
  name: 'Counter',
  impl: (domain) => {
    const CounterState = domain.state({
      name: 'CounterState',
      default: 0,
    });

    const incre = domain.command({
      name: 'increCommand',
      impl: ({ get }) => {
        const count = get(CounterState());
        return CounterState().new(count + 1);
      },
    });

    return {
      query: {
        count: CounterState.query,
      },
      command: {
        incre,
      },
    };
  },
});

export const CounterApp = () => {
  const counter = useRemeshDomain(Counter());
  const count = useRemeshQuery(counter.query.count());

  const handleIncre = () => {
    counter.command.incre();
  };

  return (
    <div
      style={{
        width: 400,
        border: '1px solid #eaeaea',
        boxSizing: 'border-box',
        padding: 10,
      }}
    >
      <h2>Counter</h2>
      <input type="number" readOnly value={count} />
      <label>
        <button onClick={handleIncre}>Count </button>{' '}
      </label>
    </div>
  );
};
