// projects/vue-demos/src/7guis/TemperatureConverter.vue
<script setup lang="ts">
import { useRemeshDomain, useRemeshQuery, useRemeshSend } from 'remesh-vue'
import { TemperatureConverterDomain } from 'remesh-domains-for-demos/dist/7guis/TemperatureConverter'

const send = useRemeshSend()
const domain = useRemeshDomain(TemperatureConverterDomain())
const celsius = useRemeshQuery(domain.query.CelsiusQuery())
const fahrenheit = useRemeshQuery(domain.query.FahrenheitQuery())

const handleCelsius = (event: Event) => {
  send(domain.command.UpdateCelsiusCommand((event.target as HTMLInputElement).value))
}

const handleFahrenheit = (event: Event) => {
  send(domain.command.UpdateFahrenheitCommand((event.target as HTMLInputElement).value))
}
</script>

<template>
  <div
    :style="{
      border: '1px solid #eaeaea',
      boxSizing: 'border-box',
      padding: '10px',
    }"
  >
    <h2>Temperature Converter</h2>
    <div>
      <input type="text" :value="celsius" @input="handleCelsius" />
      <label for="">Celsius</label>=
      <input type="text" :value="fahrenheit" @input="handleFahrenheit" />
      <label for="">Fahrenheit</label>
    </div>
  </div>
</template>

// projects/react-demos/src/7guis/TemperatureConverter.tsx
import React from 'react'
import { useRemeshDomain, useRemeshQuery, useRemeshSend } from 'remesh-react'

import { TemperatureConverterDomain } from 'remesh-domains-for-demos/dist/7guis/TemperatureConverter'

export const TemperatureConverterApp = () => {
  const send = useRemeshSend()
  const domain = useRemeshDomain(TemperatureConverterDomain())
  const celsius = useRemeshQuery(domain.query.CelsiusQuery())
  const fahrenheit = useRemeshQuery(domain.query.FahrenheitQuery())

  const handleCelsius = (event: React.ChangeEvent<HTMLInputElement>) => {
    send(domain.command.UpdateCelsiusCommand(event.target.value))
  }

  const handleFahrenheit = (event: React.ChangeEvent<HTMLInputElement>) => {
    send(domain.command.UpdateFahrenheitCommand(event.target.value))
  }

  return (
    <div
      style={{
        border: '1px solid #eaeaea',
        boxSizing: 'border-box',
        padding: 10,
      }}
    >
      <h2>Temperature Converter</h2>
      <div>
        <input type="text" value={celsius} onChange={handleCelsius} />
        <label htmlFor="">Celsius</label>=
        <input type="text" value={fahrenheit} onChange={handleFahrenheit} />
        <label htmlFor="">Fahrenheit</label>
      </div>
    </div>
  )
}
