// projects/react-demos/src/7guis/FlightBooker.tsx
import React from 'react'
import { useRemeshDomain, useRemeshQuery, useRemeshSend } from 'remesh-react'

import { FlightBookerDomain, FlightBookerOption } from 'remesh-domains-for-demos/dist/7guis/FlightBooker'

export const FlightBookerApp = () => {
  const send = useRemeshSend()
  const flightBooker = useRemeshDomain(FlightBookerDomain())
  const option = useRemeshQuery(flightBooker.query.OptionQuery())
  const status = useRemeshQuery(flightBooker.query.StatusQuery())

  const startDateInput = useRemeshQuery(flightBooker.query.StartDateInputQuery())
  const endDateInput = useRemeshQuery(flightBooker.query.EndDateInputQuery())

  const handleOptionChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    send(flightBooker.command.UpdateOptionCommand(event.target.value as FlightBookerOption))
  }

  const handleStartDateChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    send(flightBooker.command.UpdateStartDateCommand(event.target.value))
  }

  const handleEndDateChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    send(flightBooker.command.UpdateEndDateCommand(event.target.value))
  }

  const handleBookButtonClick = () => {
    if (status.bookButton === 'enabled') {
      if (option === 'one-way') {
        alert(`You have booked a one-way flight on ${startDateInput}`)
      } else {
        alert(`You have booked return flight from ${startDateInput} to ${endDateInput}`)
      }
    }
  }

  return (
    <div
      style={{
        width: 400,
        border: '1px solid #eaeaea',
        boxSizing: 'border-box',
        padding: 10,
      }}
    >
      <h2>Flight Booker</h2>
      <div>
        <select value={option} onChange={handleOptionChange}>
          <option value="one-way">One-way flight</option>
          <option value="return">Return flight</option>
        </select>
      </div>
      <div>
        <input
          type="text"
          style={{
            backgroundColor: status.startDate === 'invalid' ? 'red' : '',
          }}
          value={startDateInput}
          onChange={handleStartDateChange}
        />
      </div>
      <div>
        <input
          type="text"
          style={{
            backgroundColor: status.endDate === 'invalid' ? 'red' : '',
          }}
          disabled={status.endDate === 'disabled'}
          value={endDateInput}
          onChange={handleEndDateChange}
        />
      </div>
      <div>
        <button disabled={status.bookButton === 'disabled'} onClick={handleBookButtonClick}>
          Book
        </button>
      </div>
    </div>
  )
}

// projects/vue-demos/src/7guis/FlightBooker.vue
<script setup lang="ts">
import { useRemeshDomain, useRemeshQuery, useRemeshSend } from 'remesh-vue'

import { FlightBookerDomain, FlightBookerOption } from 'remesh-domains-for-demos/dist/7guis/FlightBooker'

const send = useRemeshSend()
const flightBookerDomain = useRemeshDomain(FlightBookerDomain())
const option = useRemeshQuery(flightBookerDomain.query.OptionQuery())
const status = useRemeshQuery(flightBookerDomain.query.StatusQuery())

const startDateInput = useRemeshQuery(flightBookerDomain.query.StartDateInputQuery())
const endDateInput = useRemeshQuery(flightBookerDomain.query.EndDateInputQuery())

const handleOptionChange = (event: Event) => {
  send(flightBookerDomain.command.UpdateOptionCommand((event.target as HTMLSelectElement).value as FlightBookerOption))
}

const handleStartDateChange = (event: Event) => {
  send(flightBookerDomain.command.UpdateStartDateCommand((event.target as HTMLInputElement).value))
}

const handleEndDateChange = (event: Event) => {
  send(flightBookerDomain.command.UpdateEndDateCommand((event.target as HTMLInputElement).value))
}

const handleBookButtonClick = () => {
  if (status.value.bookButton === 'enabled') {
    if (option.value === 'one-way') {
      alert(`You have booked a one-way flight on ${startDateInput.value}`)
    } else {
      alert(`You have booked return flight from ${startDateInput.value} to ${endDateInput.value}`)
    }
  }
}
</script>

<template>
  <div
    :style="{
      width: '400px',
      border: '1px solid #eaeaea',
      boxSizing: 'border-box',
      padding: '10px',
    }"
  >
    <h2>Flight Booker</h2>
    <div>
      <select :value="option" @input="handleOptionChange">
        <option value="one-way">One-way flight</option>
        <option value="return">Return flight</option>
      </select>
    </div>
    <div>
      <input
        type="text"
        :style="{
          backgroundColor: status.startDate === 'invalid' ? 'red' : '',
        }"
        :value="startDateInput"
        @input="handleStartDateChange"
      />
    </div>
    <div>
      <input
        type="text"
        :style="{
          backgroundColor: status.endDate === 'invalid' ? 'red' : '',
        }"
        :disabled="status.endDate === 'disabled'"
        :value="endDateInput"
        @input="handleEndDateChange"
      />
    </div>
    <div>
      <button :disabled="status.bookButton === 'disabled'" @click="handleBookButtonClick">Book</button>
    </div>
  </div>
</template>
